# === OpenStack ===
[os-global]
DOMAIN = Default
TENANT = admin

[nova]
NOVA_SERVER = 192.168.0.1
NOVA_PROTOCOL = http
NOVA_PORT = 8774
NOVA_URL = /v2.1
[nova.images]
DEBIAN = 161ec51a-e857-4418-927b-2378d325e879
CIRROS = 787da6ff-fbb6-481e-b25e-a35ac040efbe
[nova.flavors]
SMALL = 886f3bc6-e52e-4bcf-80df-0f80144a1cee
LARGE = 1
[nova.availability-zones]
ZONES = az-agent-1,az-agent-2
[nova.compute-nodes]
NODES = 192.168.0.3,192.168.0.4  # must be a list. If only one element - put ',' at the end

# === SDN ===
[global]
WEB_SERVER = 192.168.0.2
WEB_PORT = 8082
BASE_URL = /
use_ssl = False

[controller]
NODES = 192.168.0.2,  # must be a list. If only one element - put ',' at the end
INTROSPECT_PORT = 8083

# === Common ===
[auth]
AUTHN_TYPE = keystone
AUTHN_PROTOCOL = http
AUTHN_SERVER = 192.168.0.1
AUTHN_PORT = 5000
AUTHN_URL = /v3/auth/tokens
AUTHN_DOMAIN = Default
AUTHN_TENANT = admin
AUTHN_USER = admin
AUTHN_PASSWORD = contrail123
